export const actions = {
  userActionTypes: {
    SET_USER: 'SET_USER'
  },
  windowActionTypes: {
    GET_RESOLUTION: 'GET_RESOLUTION'
  },




  // samples
  basic: {
    ADD_QUESTION: 'ADD_QUESTION',
    DELETE_QUESTION: 'DELETE_QUESTION',
    DELETE_SKILL: 'DELETE_SKILL',
    ADD_SKILL: 'ADD_SKILL',
    REORDER_SKILLS: 'REORDER_SKILLS',
    REORDER_QUESTIONS: 'REORDER_QUESTIONS',
    ADD_COMMENT: 'ADD_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    UPDATE_COMMENT: 'UPDATE_COMMENT',
    UPDATE_RATING: 'UPDATE_RATING',
    CREATE_ALERT: 'CREATE_ALERT',
    DELETE_ALERT: 'DELETE_ALERT',
    RESET_CHECKLIST_VIEWER: 'RESET_CHECKLIST_VIEWER'
  },
  questions: {
    FETCH_QUESTIONS_LIST: 'FETCH_QUESTIONS_LIST',
    FETCH_QUESTION_INFO: 'FETCH_QUESTION_INFO',
    FETCH_QUESTIONS: 'FETCH_QUESTIONS',
    UPDATE_QUESTION: 'UPDATE_QUESTION',
    CREATE_QUESTION: 'CREATE_QUESTION',
    DELETE_QUESTION: 'DELETE_QUESTIONS',
    IMPORT_QUESTION: 'IMPORT_QUESTIONS'
  }
};
